@baseURL = https://localhost:5001

###
GET {{baseURL}}/api/v1/Employees

###
POST {{baseURL}}/api/v1/Employees
Content-Type: application/json

{
  "firstName": "Ivan",
  "secondName": "Petrov",
  "email": "Petrov@somemail.ru",
  "appliedPromocodesCount": 0
}

###
PUT {{baseURL}}/api/v1/Employees/f766e2bf-340a-46ea-bff3-f1700b435895
Content-Type: application/json

{
  "firstName": "Петя",
  "lastName": "Андреев",
  "email": "andreevNew@somemail.ru",
  "appliedPromocodesCount": 5
}