@baseURL = https://localhost:5001

###
GET {{baseURL}}/api/v1/Employees

###
POST {{baseURL}}/api/v1/Employees
Content-Type: application/json

{
  "firstName": "Ivan",
  "secondName": "Petrov",
  "email": "Petrov@somemail.ru",
  "appliedPromocodesCount": 0
}